[package]
name = "ttl-cache"
version = "0.1.0"
authors = ["Teo Klestrup RÃ¶ijezon <teo@nullable.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.14"
